name: Update data bundle

on:
  schedule:
    - cron: "0 8 * * *" # 3 AM Eastern (8 AM UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Update NBA data
        run: |
          python3 tools/update_nba_historical.py

      - name: Commit updated data
        env:
          GH_PAT: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "Auto Data Updater"
          git config --global user.email "runner@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/adeglin/Fantasy-Basketball-Sleeper-.git
          git add docs/data/nba_historical.json || echo "No file found to add"
          git commit -m "Automated data update [skip ci]" || echo "No changes"
          git push origin main
